# https://docs.gitlab.com/ce/ci/yaml/README.html

before_script: # bash
- python3 --version

build:p27:
  image: python:2.7-stretch
  script:
  - echo "Getting PyPI Requirements..."
  - pip install -r ./requirements.txt
  - echo "Installing..."
  - pip install -e .
  - echo "Running Flake..."
  - pip install flake8 --upgrade
  - python -m flake8 --config=tox.ini ./pytio/
  - echo "Running tests..."
  - python -m unittest -v test_tio

build:p35:
  image: python:3.5-stretch
  script:
  - echo "Getting PyPI Requirements..."
  - pip3 install -r ./requirements.txt
  - echo "Installing..."
  - pip3 install -e .
  - echo "Running Flake..."
  - pip3 install flake8 --upgrade
  - python3 -m flake8 --config=tox.ini ./pytio/
  - echo "Running tests..."
  - python3 -m unittest -v test_tio

build:p36:
  image: python:3.6-stretch
  script:
  - echo "Getting PyPI Requirements..."
  - pip3 install -r ./requirements.txt
  - echo "Installing..."
  - pip3 install -e .
  - echo "Running Flake..."
  - pip3 install flake8 --upgrade
  - python3 -m flake8 --config=tox.ini ./pytio/
  - echo "Running tests..."
  - python3 -m unittest -v test_tio

build:p37:
  image: python:3.7-stretch
  script:
  - echo "Getting PyPI Requirements..."
  - pip3 install -r ./requirements.txt
  - echo "Installing..."
  - pip3 install -e .
  - echo "Running Flake..."
  - pip3 install flake8 --upgrade
  - python3 -m flake8 --config=tox.ini ./pytio/
  - echo "Running tests..."
  - python3 -m unittest -v test_tio